name = "Kiritsune Gomen 1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5ed32c2d0d239d0cf7b849da314713e463efb70e49f0ab16e8980380a55cd90"

[versions]
fabric = "0.16.12"
minecraft = "1.21.5"
