name = "Kiritsune Gomen 1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cc2fb6166db2d00bb8dabb45b30a0e13d60a9e02f776d421c419f799652a5cc"

[versions]
fabric = "0.16.12"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks/"
