name = "Kiritsune Gomen 1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f667e5e02f12c7c2e4ae838861de779e6e1c949f9222946231dea734cb2c4ade"

[versions]
fabric = "0.16.12"
minecraft = "1.21.4"
