name = "Kiritsune Gomen 1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de4d38f6e66b102e07f91c77ef16a648536f710b1bdc546202b1bdf29a0a934e"

[versions]
fabric = "0.16.12"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks/"
