name = "Kiritsune Gomen 1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23cc9f476a6ac144290203d1151868ec8d80acafa2168cd26083eeb50a4af7c8"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
