name = "Kiritsune Gomen 1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d006998597fdbcd7f66071b71d8d238821a31f2b9b67b50d19d420bbe300dfd2"

[versions]
fabric = "0.16.12"
minecraft = "1.21.5"
