name = "Kiritsune Gomen 1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a50881b80348624c7e201300d98b95f9e1b646acfb72b6a4c58d3032a27fc4eb"

[versions]
fabric = "0.16.12"
minecraft = "1.20.1"
