name = "Kiritsune Gomen 1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dd9378c8ced39e14744bc6b127dbee21a6ebfb6656202a53840fb5c2f74c91a"

[versions]
fabric = "0.16.12"
minecraft = "1.21.5"
