name = "Kiritsune Gomen 1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c6c90b7a3f5fa8011c995ad0adcfdbb4e0a69106d8aa027b1733fd3e4b17529"

[versions]
fabric = "0.16.12"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks/"
