name = "Kiritsune Gomen 1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed757b12e667f017482c750f6544cdb38fb79b1cfd055d9865cbd3f255a5fd5c"

[versions]
fabric = "0.16.12"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks/"
