name = "Kiritsune Gomen 1 . 20 . 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6bdd860fd6c3f4a233216a0e6bd109cc9a5432c1eb0426229c0ee966f2a5ff3"

[versions]
fabric = "0.16.12"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks/"
